import type { Hazard } from "../types/hazards/types";

export const HAZARDS_DATA: Hazard[] = [
  {
    id: "haz-1",
    title: "Severe Cyclone Warning",
    description: "A severe cyclonic storm is developing off the coast with wind speeds exceeding 80 knots. Sea conditions will be extremely rough.",
    level: "danger",
    distance: 8,
    timestamp: "10 mins ago",
    coordinates: { lat: 9.85, lng: 76.10 },
    action: "Return to port immediately. Secure all loose gear and monitor radio channel 16 for updates.",
    source: "IMD Cyclone Bulletin",
    affectedArea: "Within 50km of Ernakulam coast",
    validUntil: "Tomorrow 12:00 PM"
  },
  {
    id: "haz-2",
    title: "Severe Squall Warning",
    description: "Sudden wind shifts and heavy rain expected. Visibility will be significantly reduced.",
    level: "danger",
    distance: 12,
    timestamp: "30 mins ago",
    coordinates: { lat: 9.92, lng: 76.01 },
    action: "Avoid small craft operations. Head to the nearest safe harbor.",
    source: "INCOIS Alert",
    affectedArea: "Vypin to Fort Kochi",
    validUntil: "Today 6:00 PM"
  },
  {
    id: "haz-3",
    title: "High Swell Alert",
    description: "Swell heights reaching 2.5m to 3.5m in the open sea due to distant storm activity.",
    level: "warning",
    distance: 25,
    timestamp: "1 hour ago",
    coordinates: { lat: 9.75, lng: 75.82 },
    action: "Exercise caution. Small boats should avoid deep-sea fishing.",
    source: "INCOIS Ocean State Forecast",
    affectedArea: "Offshore waters beyond 20km",
    validUntil: "Tomorrow 6:00 AM"
  },
  {
    id: "haz-4",
    title: "Lightning Activity",
    description: "Intense thunderstorm cells with frequent lightning strikes detected in the coastal belt.",
    level: "warning",
    distance: 35,
    timestamp: "2 hours ago",
    coordinates: { lat: 10.12, lng: 76.05 },
    action: "Lower tall antennas if possible. Stay inside the cabin and avoid touching metal structures.",
    source: "Local Weather Radar",
    affectedArea: "Northern coastal sectors",
    validUntil: "Today 8:00 PM"
  },
  {
    id: "haz-5",
    title: "Strong Current Advisory",
    description: "Unusually strong underwater currents detected, which may affect net deployment and retrieval.",
    level: "warning",
    distance: 18,
    timestamp: "3 hours ago",
    coordinates: { lat: 9.88, lng: 75.95 },
    action: "Be cautious when deploying nets. Expect drift and adjust anchoring accordingly.",
    source: "Oceanographic Sensor Network",
    affectedArea: "Coastal shelf edge",
    validUntil: "Tomorrow 12:00 AM"
  },
  {
    id: "haz-6",
    title: "Rip Current Warning",
    description: "Dangerous rip currents observed near the river mouth. High risk of vessels being pulled off course.",
    level: "warning",
    distance: 5,
    timestamp: "4 hours ago",
    coordinates: { lat: 9.96, lng: 76.23 },
    action: "Maintain higher engine RPM when navigating the inlet. Do not stop engine near the mouth.",
    source: "Port Authority",
    affectedArea: "River mouth and harbor entrance",
    validUntil: "Today 10:00 PM"
  },
  {
    id: "haz-7",
    title: "High Wave Alert",
    description: "Periodic large waves exceeding normal operational limits expected in the deeper channels.",
    level: "warning",
    distance: 30,
    timestamp: "5 hours ago",
    coordinates: { lat: 9.70, lng: 75.75 },
    action: "Ensure all crew are wearing life jackets. Secure cargo.",
    source: "IMD Marine Division",
    affectedArea: "Shipping lane approaches",
    validUntil: "Tomorrow 8:00 AM"
  },
  {
    id: "haz-8",
    title: "Marine Boundary Proximity",
    description: "You are approaching the international maritime boundary line.",
    level: "warning",
    distance: 40,
    timestamp: "10 mins ago",
    coordinates: { lat: 9.50, lng: 75.50 },
    action: "Check your coordinates and alter course to stay within domestic waters.",
    source: "Coast Guard Tracking",
    affectedArea: "Western outer limits",
    validUntil: "Ongoing"
  },
  {
    id: "haz-9",
    title: "Low Visibility Fog",
    description: "Dense fog patches reported, reducing visibility to less than 500 meters.",
    level: "info",
    distance: 15,
    timestamp: "1 hour ago",
    coordinates: { lat: 10.05, lng: 76.15 },
    action: "Sound fog signals. Proceed at safe speed and keep sharp lookout.",
    source: "Coastal Observers",
    affectedArea: "Northern fishing zones",
    validUntil: "Today 11:00 AM"
  },
  {
    id: "haz-10",
    title: "Fishing Ban Notice",
    description: "Annual trawling ban is in effect to promote fish breeding. Mechanized boats are prohibited.",
    level: "info",
    distance: 0,
    timestamp: "1 day ago",
    coordinates: { lat: 9.98, lng: 76.28 },
    action: "Traditional fishing allowed. Mechanized vessels must remain in port.",
    source: "Fisheries Department",
    affectedArea: "Entire coastal state",
    validUntil: "July 31st"
  }
];
