export { default as LandingPage } from "./LandingPage";
export { default as HeroSection } from "./HeroSection";
export { default as InfoSection } from "./InfoSection";
export { default as FeatureCarousel } from "./FeatureCarousel";
export { default as SocialProofSection } from "./SocialProofSection";
export { default as PricingSection } from "./PricingSection";
export { default as FAQSection } from "./FAQSection";
export { default as CTASection } from "./CTASection";
export { default as FooterSection } from "./FooterSection";
